apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-adminer
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: "{{ .Values.adminer.image.repository }}:{{ .Values.adminer.image.tag }}"
        imagePullPolicy: {{ .Values.adminer.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.adminer.port }}