apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-adminer
  labels:
    app: adminer
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.adminer.port }}
    targetPort: {{ .Values.adminer.port }}
  selector:
    app: adminer

