apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        ports:
        - containerPort: {{ .Values.db.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.db.environment.MYSQL_ROOT_PASSWORD }}
        - name: MYSQL_DATABASE
          value: {{ .Values.db.environment.MYSQL_DATABASE }}
        - name: MYSQL_USER
          value: {{ .Values.db.environment.MYSQL_USER }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.db.environment.MYSQL_PASSWORD }}
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      # asegurarte de que solo esté marcado como listo cuando pueda aceptar conexiones
      readinessProbe:
        exec:
          command:
          - /bin/sh
          - -c
            mysqladmin ping -h localhost --silent
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3    
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: mysql-data