apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-phpmyadmin
  labels:
    app: php
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.phpmyadmin.port }}
    targetPort: {{ .Values.phpmyadmin.port }}
  selector:
    app: phpmyadmin

