apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-php
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      initContainers:
      - name: copy-data
        image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Waiting for database to be ready..." && \
          until mysqladmin ping -h {{ .Release.Name }}-db --silent; do
            sleep 2;
            echo "Still waiting for database...";
          done;

          echo "Copying data to persistent volume..." && \
          cp -R /var/www/* /mnt/www && \

          if [ -f /var/www/.env ]; then
            cp /var/www/.env /mnt/www/.env;
            sed -i 's/^DB_HOST=.*/DB_HOST={{ .Release.Name }}-db/' /mnt/www/.env;
            echo "Cambio en .env"
          fi && \

          if [ -f /var/www/.env.example ]; then
            cp /var/www/.env.example /mnt/www/.env.example;
            sed -i 's/^DB_HOST=.*/DB_HOST={{ .Release.Name }}-db/' /mnt/www/.env;
            echo "Cambio en .env.example"
          fi && \

          ls -la /mnt/www && \

          chown -R www-data:www-data /mnt/www && \
          chmod -R 775 /mnt/www
        volumeMounts:
        - name: php-code
          mountPath: /mnt/www
      containers:
      - name: php
        image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
        ports:
        - containerPort: {{ .Values.php.port }}
        volumeMounts:
        - name: php-code
          mountPath: /var/www
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ ! -f /var/www/composer.json ]; then
            echo "composer.json not found in /var/www. Exiting.";
            exit 1;
          fi;
          chown -R www-data:www-data /var/www && \
          chmod -R 775 /var/www && \
          composer setup && \
          php-fpm
      volumes:
      - name: php-code
        persistentVolumeClaim:
          claimName: php-storage
