apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.php.name }}"
  labels:
    app: {{ .Values.php.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.php.port }}
    targetPort: {{ .Values.php.port }}
  selector:
    app: {{ .Values.php.name }}
