apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-php
  labels:
    app: php
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.php.port }}
    targetPort: {{ .Values.php.port }}
  selector:
    app: php
