apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-php
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      initContainers:
      - name: copy-data
        image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Copying data to persistent volume..." && \
          cp -R /var/www/* /mnt/www && \
          chown -R www-data:www-data /mnt/www && \
          chmod -R 775 /mnt/www
        volumeMounts:
        - name: php-code
          mountPath: /mnt/www
      containers:
      - name: php
        image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
        ports:
        - containerPort: {{ .Values.php.port }}
        volumeMounts:
        - name: php-code
          mountPath: /var/www
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ ! -f /var/www/composer.json ]; then
            echo "composer.json not found in /var/www. Exiting.";
            exit 1;
          fi;
          chown -R www-data:www-data /var/www && \
          chmod -R 775 /var/www && \
          composer install --working-dir=/var/www && \
          npm install && npm run build && \
          php-fpm
      volumes:
      - name: php-code
        persistentVolumeClaim:
          claimName: php-storage
