apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.redis.name }}"
  labels:
    app: {{ .Values.redis.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
      - name: {{ .Values.redis.name }}
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: {{ .Values.redis.port }}
        command:
        - "redis-server"
        args:
        - "--appendonly"
        - "yes"
        volumeMounts:
        - name: {{ .Values.redis.pvc.name }}
          mountPath: /data
      volumes:
      - name: {{ .Values.redis.pvc.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.redis.pvc.name }}