apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.redis.name }}"
  labels:
    app: {{ .Values.redis.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
  selector:
    app: {{ .Values.redis.name }}